# -*- coding: utf-8 -*-
"""02_finetuning_distilbert_imdb_v3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mj_fTi4uBlkVceIkrVYiQKGeaJ3YQ4Rt
"""

# ============================================================
# 1. Instalación de librerías
# ============================================================

!pip install -q datasets transformers evaluate accelerate scikit-learn matplotlib

# Se desinstala torchvision porque no es necesario para clasificación de texto
# y puede generar conflictos de compatibilidad con datasets en Colab.
!pip uninstall -y torchvision

# ============================================================
# 2. Importaciones y configuración inicial
# ============================================================

import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch

from datasets import load_dataset
from transformers import AutoTokenizer, set_seed

SEED = 42

set_seed(SEED)
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Dispositivo disponible:", device)

# ============================================================
# 3. Carga del dataset IMDb desde Hugging Face
# ============================================================

dataset = load_dataset("stanfordnlp/imdb")

print(dataset)

# ============================================================
# 4. Exploración inicial del conjunto de entrenamiento
# ============================================================

df_train = pd.DataFrame(dataset["train"])

print("Cantidad de muestras de entrenamiento:", len(df_train))
display(df_train.head())

print("\nValores nulos:")
print(df_train.isnull().sum())

textos_vacios = (df_train["text"].str.strip() == "").sum()
print("\nCantidad de reseñas vacías:", textos_vacios)

# ============================================================
# 5. Balance de clases
# ============================================================

conteo_clases = df_train["label"].value_counts().sort_index()

plt.figure(figsize=(6, 4))
conteo_clases.plot(kind="bar")
plt.title("Balance de clases en IMDb")
plt.xlabel("Clase")
plt.ylabel("Cantidad de reseñas")
plt.xticks(ticks=[0, 1], labels=["Negativo", "Positivo"], rotation=0)
plt.tight_layout()
plt.show()

print(conteo_clases)

# ============================================================
# 6. Distribución aproximada de longitud de reseñas
# ============================================================

df_train["word_count"] = df_train["text"].apply(lambda x: len(x.split()))

plt.figure(figsize=(8, 5))
plt.hist(df_train["word_count"], bins=50, alpha=0.8)
plt.axvline(x=512, linestyle="--", label="Referencia: 512 tokens")
plt.title("Distribución aproximada de longitud de reseñas")
plt.xlabel("Cantidad aproximada de palabras")
plt.ylabel("Frecuencia")
plt.legend()
plt.tight_layout()
plt.show()

print(df_train["word_count"].describe())

# ============================================================
# 7. Creación de conjuntos train, validation y test
# ============================================================

# Se separa una parte del conjunto train para validación.
# El conjunto test original se reserva para evaluación final.

train_valid_split = dataset["train"].train_test_split(
    test_size=0.2,
    seed=SEED,
    stratify_by_column="label"
)

train_dataset = train_valid_split["train"]
valid_dataset = train_valid_split["test"]
test_dataset = dataset["test"]

print("Train:", len(train_dataset))
print("Validation:", len(valid_dataset))
print("Test:", len(test_dataset))

# ============================================================
# 8. Submuestras para fine-tuning preliminar
# ============================================================
#En esta etapa se trabaja con una submuestra del dataset IMDb: 8000 ejemplos para entrenamiento, 2000 para validación y 2000 para prueba.
#Esta decisión permite validar el pipeline de fine-tuning con un costo computacional manejable.
#Los resultados reportados corresponden a esta configuración experimental y no al entrenamiento sobre la totalidad del dataset.
train_sample = train_dataset.shuffle(seed=SEED).select(range(8000))
valid_sample = valid_dataset.shuffle(seed=SEED).select(range(2000))
test_sample = test_dataset.shuffle(seed=SEED).select(range(2000))

print("Train sample:", len(train_sample))
print("Validation sample:", len(valid_sample))
print("Test sample:", len(test_sample))

# ============================================================
# 9. Tokenización con DistilBERT
# ============================================================

# PRIMERO: Guardar labels originales
train_labels = np.array(train_sample['label'])
valid_labels = np.array(valid_sample['label'])
test_labels = np.array(test_sample['label'])

MODEL_NAME = "distilbert-base-uncased"
MAX_LENGTH = 256

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        truncation=True,
        padding="max_length",
        max_length=MAX_LENGTH
    )

tokenized_train = train_sample.map(tokenize_function, batched=True)
tokenized_valid = valid_sample.map(tokenize_function, batched=True)
tokenized_test = test_sample.map(tokenize_function, batched=True)

print("Tokenización completada.")

# ============================================================
# 10. Preparación del dataset tokenizado
# ============================================================

columnas_a_eliminar = ["text"]

tokenized_train = tokenized_train.remove_columns(columnas_a_eliminar)
tokenized_valid = tokenized_valid.remove_columns(columnas_a_eliminar)
tokenized_test = tokenized_test.remove_columns(columnas_a_eliminar)

tokenized_train = tokenized_train.rename_column("label", "labels")
tokenized_valid = tokenized_valid.rename_column("label", "labels")
tokenized_test = tokenized_test.rename_column("label", "labels")

# No usamos set_format("torch") para evitar conflicto con torchvision en Colab
print(tokenized_train)

# ============================================================
# 11. Carga del modelo DistilBERT para clasificación binaria
# ============================================================

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=2
)

model.to(device)

# ============================================================
# 12. Métricas de evaluación
# ============================================================

import evaluate

accuracy_metric = evaluate.load("accuracy")
precision_metric = evaluate.load("precision")
recall_metric = evaluate.load("recall")
f1_metric = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)

    accuracy = accuracy_metric.compute(
        predictions=predictions,
        references=labels
    )["accuracy"]

    precision = precision_metric.compute(
        predictions=predictions,
        references=labels,
        average="binary"
    )["precision"]

    recall = recall_metric.compute(
        predictions=predictions,
        references=labels,
        average="binary"
    )["recall"]

    f1 = f1_metric.compute(
        predictions=predictions,
        references=labels,
        average="binary"
    )["f1"]

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

# ============================================================
# 13. Configuración del entrenamiento
# ============================================================

from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="./resultados_distilbert_imdb",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=2,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="steps",
    logging_steps=50,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,
    save_total_limit=2,
    report_to="none"
)

# ============================================================
# Resumen de configuración experimental
# ============================================================

configuracion = {
    "Modelo base": MODEL_NAME,
    "Dataset principal": "stanfordnlp/imdb",
    "Muestras de entrenamiento": len(train_sample),
    "Muestras de validación": len(valid_sample),
    "Muestras de prueba": len(test_sample),
    "Longitud máxima": f"{MAX_LENGTH} tokens",
    "Learning rate": training_args.learning_rate,
    "Batch size entrenamiento": training_args.per_device_train_batch_size,
    "Batch size evaluación": training_args.per_device_eval_batch_size,
    "Épocas": training_args.num_train_epochs,
    "Dispositivo": device
}

for clave, valor in configuracion.items():
    print(f"{clave}: {valor}")

# ============================================================
# 14. Inicialización del Trainer
# ============================================================

from transformers import DataCollatorWithPadding

data_collator = DataCollatorWithPadding(
    tokenizer=tokenizer,
    return_tensors="pt"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_valid,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    processing_class=tokenizer
)

# ============================================================
# 15. Fine-tuning
# ============================================================

import time

inicio = time.time()

train_result = trainer.train()

fin = time.time()
tiempo_entrenamiento = fin - inicio

print(f"Tiempo total de entrenamiento: {tiempo_entrenamiento/60:.2f} minutos")

# ============================================================
# 16. Evaluación en validación
# ============================================================

valid_results = trainer.evaluate(tokenized_valid)

print("--- Resultados en validación ---")
for key, value in valid_results.items():
    print(f"{key}: {value}")

# ============================================================
# 17. Evaluación final en test
# ============================================================

test_results = trainer.evaluate(tokenized_test)

print("--- Resultados en test ---")
for key, value in test_results.items():
    print(f"{key}: {value}")

# ============================================================
# 18. Guardado del modelo y tokenizer
# ============================================================

trainer.save_model("./modelo_distilbert_imdb")
tokenizer.save_pretrained("./modelo_distilbert_imdb")

print("Modelo y tokenizer guardados correctamente.")

# ============================================================
# 20. Tabla comparativa de métricas
# ============================================================

import pandas as pd

resultados_comparativos = pd.DataFrame({
    "Métrica": ["Loss", "Accuracy", "Precision", "Recall", "F1-score"],
    "Validación": [
        valid_results["eval_loss"],
        valid_results["eval_accuracy"],
        valid_results["eval_precision"],
        valid_results["eval_recall"],
        valid_results["eval_f1"]
    ],
    "Test": [
        test_results["eval_loss"],
        test_results["eval_accuracy"],
        test_results["eval_precision"],
        test_results["eval_recall"],
        test_results["eval_f1"]
    ]
})

display(resultados_comparativos)

# ============================================================
# 21. Comparación contra baseline preliminar
# ============================================================

baseline_accuracy = 0.8520
baseline_precision = 0.8440
baseline_f1 = 0.8508

comparacion_baseline = pd.DataFrame({
    "Métrica": ["Accuracy", "Precision", "F1-score"],
    "Baseline Entregable 1": [
        baseline_accuracy,
        baseline_precision,
        baseline_f1
    ],
    "Modelo actual - Test": [
        test_results["eval_accuracy"],
        test_results["eval_precision"],
        test_results["eval_f1"]
    ]
})

comparacion_baseline["Mejora absoluta"] = (
    comparacion_baseline["Modelo actual - Test"] -
    comparacion_baseline["Baseline Entregable 1"]
)

display(comparacion_baseline)

# ============================================================
# 22. Matriz de confusión sobre el conjunto de prueba
# ============================================================

import numpy as np
import matplotlib.pyplot as plt

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

predictions_output = trainer.predict(tokenized_test)

y_pred = np.argmax(predictions_output.predictions, axis=-1)
y_true = predictions_output.label_ids

cm = confusion_matrix(y_true, y_pred)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Negativo", "Positivo"]
)

disp.plot(values_format="d")
plt.title("Matriz de confusión - DistilBERT en IMDb")
plt.tight_layout()
plt.show()

print("Matriz de confusión:")
print(cm)

"""### Interpretación de la matriz de confusión

La matriz de confusión muestra que el modelo clasifica correctamente 888 reseñas negativas y 914 reseñas positivas, sobre un total de 2000 ejemplos de prueba. El modelo comete 112 falsos positivos, es decir, reseñas negativas clasificadas como positivas, y 86 falsos negativos, es decir, reseñas positivas clasificadas como negativas.

Esto indica que el modelo tiene un desempeño equilibrado entre ambas clases, aunque presenta una ligera tendencia a predecir la clase positiva en algunos casos donde la reseña era negativa. Esta observación coincide con el reporte de clasificación, donde la clase positiva obtiene mayor recall, mientras que la clase negativa obtiene mayor precision.

En comparación con el baseline del entregable inicial, el modelo actual mejora de 85.20% a 90.10% en accuracy y de 85.08% a 90.23% en F1-score. Por tanto, el fine-tuning realizado sobre DistilBERT mejora claramente el rendimiento preliminar del proyecto.
"""

# ============================================================
# 23. Reporte de clasificación por clase
# ============================================================

from sklearn.metrics import classification_report

reporte = classification_report(
    y_true,
    y_pred,
    target_names=["Negativo", "Positivo"],
    digits=4
)

print(reporte)

# ============================================================
# 24. Conteo de tipos de error
# ============================================================

tn, fp, fn, tp = cm.ravel()

print(f"Verdaderos negativos (TN): {tn}")
print(f"Falsos positivos (FP): {fp}")
print(f"Falsos negativos (FN): {fn}")
print(f"Verdaderos positivos (TP): {tp}")

if fp > fn:
    print("\nEl modelo comete más falsos positivos: tiende a clasificar algunas reseñas negativas como positivas.")
elif fn > fp:
    print("\nEl modelo comete más falsos negativos: tiende a clasificar algunas reseñas positivas como negativas.")
else:
    print("\nEl modelo presenta la misma cantidad de falsos positivos y falsos negativos.")

"""### Análisis de resultados

El modelo fine-tuneado con DistilBERT obtuvo un desempeño sólido en la tarea de clasificación binaria de sentimientos sobre IMDb. En validación alcanzó un accuracy de 88.55% y un F1-score de 88.68%, mientras que en el conjunto de prueba obtuvo un accuracy de 90.10% y un F1-score de 90.23%.

En comparación con el entrenamiento preliminar reportado en el entregable inicial, el modelo actual muestra una mejora clara. El baseline inicial alcanzaba aproximadamente 85.20% de accuracy y 85.08% de F1-score, mientras que la versión actual supera el 90% de F1-score en prueba.

La matriz de confusión permite identificar si el modelo presenta mayor dificultad con reseñas positivas o negativas. En particular, los falsos positivos corresponden a reseñas negativas clasificadas erróneamente como positivas, mientras que los falsos negativos corresponden a reseñas positivas clasificadas como negativas. Este análisis permite pasar de una evaluación general basada en métricas agregadas a una revisión más detallada del comportamiento del clasificador.

**#################################################################################**

**-----------------------------------ANÁLISIS DE ERRORES E INTERPRETABILIDAD-----------------------------------**

**#################################################################################**
"""

# ============================================================
# RECARGA DEL MODELO CON ATTENTION WEIGHTS
# ============================================================

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer

# Recargar modelo CON attention weights
model = AutoModelForSequenceClassification.from_pretrained(
    "./modelo_distilbert_imdb",
    attn_implementation="eager"
)

# Mover a GPU/CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

print(f"✅ Modelo cargado en: {device}")
print(f"✅ Attention implementation: eager (soporta output_attentions)")

# ============================================================
# 25. ANÁLISIS DE ERRORES: Falsos Positivos y Falsos Negativos
# ============================================================

import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

# Obtener predicciones en test set
test_predictions = trainer.predict(tokenized_test)
pred_labels = np.argmax(test_predictions.predictions, axis=1)
pred_scores = np.max(test_predictions.predictions, axis=1)  # Confianza

true_labels = test_labels

# Crear dataframe con resultados
resultados_test = pd.DataFrame({
    'texto_original': test_sample['text'],
    'etiqueta_real': true_labels,
    'prediccion': pred_labels,
    'confianza': pred_scores,
    'es_correcto': pred_labels == true_labels
})

# Análisis de Falsos Positivos (FP): Predice POSITIVO pero es NEGATIVO
falsos_positivos = resultados_test[(resultados_test['prediccion'] == 1) &
                                     (resultados_test['etiqueta_real'] == 0)].copy()
falsos_positivos = falsos_positivos.sort_values('confianza', ascending=False)

print(f"\n📊 FALSOS POSITIVOS: {len(falsos_positivos)} casos ({len(falsos_positivos)/len(resultados_test)*100:.2f}%)")
print(f"Confianza promedio: {falsos_positivos['confianza'].mean():.4f}")
print("\nTop 10 ejemplos más confiados pero INCORRECTOS:")
print("="*100)

for idx, (i, row) in enumerate(falsos_positivos.head(10).iterrows(), 1):
    print(f"\n{idx}. FALSO POSITIVO (Confianza: {row['confianza']:.4f})")
    print(f"   Real: NEGATIVO | Predicho: POSITIVO")
    print(f"   Texto: {row['texto_original'][:150]}...")

# Análisis de Falsos Negativos (FN): Predice NEGATIVO pero es POSITIVO
falsos_negativos = resultados_test[(resultados_test['prediccion'] == 0) &
                                     (resultados_test['etiqueta_real'] == 1)].copy()
falsos_negativos = falsos_negativos.sort_values('confianza', ascending=False)

print(f"\n\n📊 FALSOS NEGATIVOS: {len(falsos_negativos)} casos ({len(falsos_negativos)/len(resultados_test)*100:.2f}%)")
print(f"Confianza promedio: {falsos_negativos['confianza'].mean():.4f}")
print("\nTop 10 ejemplos más confiados pero INCORRECTOS:")
print("="*100)

for idx, (i, row) in enumerate(falsos_negativos.head(10).iterrows(), 1):
    print(f"\n{idx}. FALSO NEGATIVO (Confianza: {row['confianza']:.4f})")
    print(f"   Real: POSITIVO | Predicho: NEGATIVO")
    print(f"   Texto: {row['texto_original'][:150]}...")

# Guardar para análisis posterior
falsos_positivos.to_csv('falsos_positivos_detallado.csv', index=False)
falsos_negativos.to_csv('falsos_negativos_detallado.csv', index=False)

# ============================================================
# 26. CARACTERÍSTICAS DE TEXTOS MAL CLASIFICADOS
# ============================================================

# Analizar longitud de texto en errores vs aciertos
resultados_test['num_palabras'] = resultados_test['texto_original'].apply(lambda x: len(x.split()))
resultados_test['num_caracteres'] = resultados_test['texto_original'].apply(lambda x: len(x))

print("\n📈 ANÁLISIS DE LONGITUD")
print("="*80)
print("\nTextos CORRECTAMENTE clasificados:")
print(f"  Palabras promedio: {resultados_test[resultados_test['es_correcto']]['num_palabras'].mean():.0f}")
print(f"  Caracteres promedio: {resultados_test[resultados_test['es_correcto']]['num_caracteres'].mean():.0f}")

print("\nTextos INCORRECTAMENTE clasificados:")
print(f"  Palabras promedio: {resultados_test[~resultados_test['es_correcto']]['num_palabras'].mean():.0f}")
print(f"  Caracteres promedio: {resultados_test[~resultados_test['es_correcto']]['num_caracteres'].mean():.0f}")

# Visualizar distribución
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Gráfico 1: Longitud vs Precisión
ax = axes[0]
correcto = resultados_test[resultados_test['es_correcto']]['num_palabras']
incorrecto = resultados_test[~resultados_test['es_correcto']]['num_palabras']
ax.hist([correcto, incorrecto], bins=30, label=['Correcto', 'Incorrecto'], alpha=0.7)
ax.set_xlabel('Número de palabras')
ax.set_ylabel('Frecuencia')
ax.set_title('Distribución de longitud: Errores vs Aciertos')
ax.legend()

# Gráfico 2: Confianza vs Acierto
ax = axes[1]
ax.scatter(resultados_test[resultados_test['es_correcto']]['confianza'],
           resultados_test[resultados_test['es_correcto']]['num_palabras'],
           alpha=0.5, label='Correcto', s=20)
ax.scatter(resultados_test[~resultados_test['es_correcto']]['confianza'],
           resultados_test[~resultados_test['es_correcto']]['num_palabras'],
           alpha=0.5, label='Incorrecto', s=20, color='red')
ax.set_xlabel('Confianza del modelo')
ax.set_ylabel('Número de palabras')
ax.set_title('Confianza vs Longitud')
ax.legend()

plt.tight_layout()
plt.savefig('error_analysis_features.png', dpi=300, bbox_inches='tight')
plt.show()

print("\n✅ Gráficos guardados en: error_analysis_features.png")

# ============================================================
# 27. INTERPRETABILIDAD: ANÁLISIS DE ATENCIÓN
# ============================================================

# Función para extraer los tokens con mayor atención
def analizar_atencion_ejemplo(text, verdadero, predicho, confianza, tokenizer, model):
    """
    Analiza qué palabras fueron importantes en la predicción
    """
    # Tokenizar
    inputs = tokenizer(text, return_tensors='pt', truncation=True, max_length=512)

    # ← AGREGAR ESTA LÍNEA: Mover a GPU si el modelo está en GPU
    device = next(model.parameters()).device
    inputs = {k: v.to(device) for k, v in inputs.items()}

    # Forward pass con output_attentions
    with torch.no_grad():
        outputs = model(**inputs, output_attentions=True)

    # Obtener atención (última capa, promediada entre cabezas)
    attention = outputs.attentions[-1]  # Última capa
    attention = attention[0].mean(dim=0)  # Promediar sobre cabezas

    # Tokens
    tokens = tokenizer.convert_ids_to_tokens(inputs['input_ids'][0])

    # Atención del token [CLS] (usado para clasificación)
    cls_attention = attention[0, 1:-1]  # Excluir [CLS] y [SEP]

    # Top 10 tokens más importantes
    top_indices = torch.topk(cls_attention, min(10, len(tokens)-2)).indices

    print(f"\n🔍 ANÁLISIS DE ATENCIÓN")
    print("="*80)
    print(f"Texto: {text[:100]}...")
    print(f"Verdadero: {'POSITIVO' if verdadero==1 else 'NEGATIVO'} | "
          f"Predicho: {'POSITIVO' if predicho==1 else 'NEGATIVO'} | "
          f"Confianza: {confianza:.4f}")
    print(f"\nTop palabras más importantes en la decisión:")

    for rank, idx in enumerate(top_indices, 1):
        token = tokens[idx+1]  # +1 porque saltamos [CLS]
        weight = cls_attention[idx].item()
        print(f"  {rank:2d}. {token:20s} (peso: {weight:.4f})")

    return tokens, cls_attention

# Analizar algunos FP y FN interesantes
print("\n" + "="*80)
print("INTERPRETACIÓN DE FALSOS POSITIVOS CLAVE")
print("="*80)

for i, row in falsos_positivos.head(3).iterrows():
    tokens, attn = analizar_atencion_ejemplo(
        row['texto_original'],
        row['etiqueta_real'],
        row['prediccion'],
        row['confianza'],
        tokenizer,
        model
    )

print("\n" + "="*80)
print("INTERPRETACIÓN DE FALSOS NEGATIVOS CLAVE")
print("="*80)

for i, row in falsos_negativos.head(3).iterrows():
    tokens, attn = analizar_atencion_ejemplo(
        row['texto_original'],
        row['etiqueta_real'],
        row['prediccion'],
        row['confianza'],
        tokenizer,
        model
    )

# ============================================================
# 28. RESUMEN Y CONCLUSIONES
# ============================================================

# PRIMERO: Recrear falsos_positivos y falsos_negativos con num_palabras
falsos_positivos = resultados_test[(resultados_test['prediccion'] == 1) &
                                     (resultados_test['etiqueta_real'] == 0)].copy()
falsos_negativos = resultados_test[(resultados_test['prediccion'] == 0) &
                                     (resultados_test['etiqueta_real'] == 1)].copy()

# Crear tabla de resumen
resumen_errores = pd.DataFrame({
    'Métrica': [
        'Total de muestras en test',
        'Total de errores',
        'Tasa de error',
        'Falsos Positivos (FP)',
        'Falsos Negativos (FN)',
        'FP como % de errores',
        'FN como % de errores',
        'Confianza promedio FP',
        'Confianza promedio FN',
        'Longitud promedio FP (palabras)',
        'Longitud promedio FN (palabras)'
    ],
    'Valor': [
        len(resultados_test),
        len(resultados_test[~resultados_test['es_correcto']]),
        f"{(1 - resultados_test['es_correcto'].mean())*100:.2f}%",
        len(falsos_positivos),
        len(falsos_negativos),
        f"{len(falsos_positivos)/(len(resultados_test[~resultados_test['es_correcto']]))*100:.2f}%",
        f"{len(falsos_negativos)/(len(resultados_test[~resultados_test['es_correcto']]))*100:.2f}%",
        f"{falsos_positivos['confianza'].mean():.4f}",
        f"{falsos_negativos['confianza'].mean():.4f}",
        f"{falsos_positivos['num_palabras'].mean():.0f}",
        f"{falsos_negativos['num_palabras'].mean():.0f}"
    ]
})

print("\n📋 RESUMEN DE ANÁLISIS DE ERRORES")
print("="*80)
print(resumen_errores.to_string(index=False))

resumen_errores.to_csv('resumen_errores.csv', index=False)

print("\n✅ Archivos generados:")
print("   - falsos_positivos_detallado.csv")
print("   - falsos_negativos_detallado.csv")
print("   - error_analysis_features.png")
print("   - resumen_errores.csv")

"""**#################################################################################**

**---------------------------------------EVALUACIÓN CON AMAZON POLARITY---------------------------------------**

**#################################################################################**
"""

#!pip install --upgrade datasets huggingface_hub

# ============================================================
# 29. EXPLORACIÓN DE AMAZON POLARITY
# ============================================================

import requests, os
from datasets import load_dataset
import pandas as pd

print("📥 Descargando Amazon Polarity (vía archivos Parquet)...")

# --- CARGA ROBUSTA SIN BUG DE URIs ---
# 1. Obtener la lista de archivos .parquet del dataset
api_url = "https://huggingface.co/api/datasets/amazon_polarity"
info = requests.get(api_url).json()

parquet_files = [sib["rfilename"] for sib in info.get("siblings", [])
                 if sib["rfilename"].endswith(".parquet")]
print("Archivos encontrados:", parquet_files)

# 2. Descargar cada archivo (si no existe localmente)
os.makedirs("amazon_local", exist_ok=True)
for rfilename in parquet_files:
    url = f"https://huggingface.co/datasets/amazon_polarity/resolve/main/{rfilename}"
    dest = os.path.join("amazon_local", os.path.basename(rfilename))
    if not os.path.exists(dest):
        print(f"⬇️ Descargando {rfilename}...")
        resp = requests.get(url)
        if resp.status_code == 200:
            with open(dest, "wb") as f:
                f.write(resp.content)
        else:
            print(f"❌ Error {resp.status_code} al descargar {rfilename}")
    else:
        print(f"✔️ {dest} ya existe, omitiendo descarga.")

# 3. Organizar rutas de archivos para train y test
train_files = []
test_files = []
for f in os.listdir("amazon_local"):
    path = f"amazon_local/{f}"
    if "train" in f:
        train_files.append(path)
    elif "test" in f:
        test_files.append(path)

# train_files puede contener varios archivos, los pasamos como lista
data_files = {"train": train_files, "test": test_files}
print("Archivos a cargar:", data_files)

# 4. Cargar el dataset desde los archivos locales
dataset_amazon = load_dataset("parquet", data_files=data_files)
print("✅ Amazon Polarity cargado exitosamente!")

# --- FIN DE LA CARGA ---

print(f"\nSplits disponibles: {list(dataset_amazon.keys())}")

# Información básica
print("\n📊 INFORMACIÓN BÁSICA AMAZON POLARITY")
print("="*80)
print(f"Muestras de entrenamiento: {len(dataset_amazon['train'])}")
print(f"Muestras de prueba: {len(dataset_amazon['test'])}")

# Exploración
df_amazon_train = pd.DataFrame(dataset_amazon['train'])
df_amazon_test = pd.DataFrame(dataset_amazon['test'])

print(f"\nColumnas: {list(df_amazon_train.columns)}")
print(f"\nPrimera fila:")
print(df_amazon_train.iloc[0])

# Balance de clases
print("\n📈 DISTRIBUCIÓN DE CLASES")
print("Train:")
print(df_amazon_train['label'].value_counts().sort_index())
print(f"\nTest:")
print(df_amazon_test['label'].value_counts().sort_index())

# Longitud de textos
df_amazon_train['num_palabras'] = (df_amazon_train['title'].fillna('') + ' ' +
                                    df_amazon_train['content'].fillna('')).apply(lambda x: len(x.split()))

print(f"\n📏 ESTADÍSTICAS DE LONGITUD")
print(f"Promedio de palabras: {df_amazon_train['num_palabras'].mean():.0f}")
print(f"Mínimo: {df_amazon_train['num_palabras'].min()}")
print(f"Máximo: {df_amazon_train['num_palabras'].max()}")
print(f"Mediana: {df_amazon_train['num_palabras'].median():.0f}")

# Comparación IMDb vs Amazon
print("\n" + "="*80)
print("COMPARACIÓN IMDb vs Amazon Polarity")
print("="*80)
comparacion = pd.DataFrame({
    'Dataset': ['IMDb', 'Amazon Polarity'],
    'Muestras Train': [len(df_train), len(df_amazon_train)],
    'Muestras Test': [len(test_dataset), len(df_amazon_test)],
    'Palabras Promedio': [
        df_train['word_count'].mean(),
        df_amazon_train['num_palabras'].mean()
    ],
    'Balance Clases': ['Balanceado', 'Balanceado']
})
print(comparacion.to_string(index=False))

# ============================================================
# 30. PREPARACIÓN DE AMAZON POLARITY (Paso 2.2)
# ============================================================

print("⏳ Preparando Amazon Polarity...")

# Función para preparar dataset Amazon
def preparar_amazon_dataset(dataset, tokenizer, max_length=256):
    """
    Prepara Amazon Polarity con el mismo formato que IMDb
    """
    # Combinar title y content
    def combinar_texto(ejemplo):
        texto = (ejemplo['title'] + " " + ejemplo['content']).strip()
        return {'text': texto, 'label': ejemplo['label']}

    # Aplicar transformación
    dataset_preparado = dataset.map(combinar_texto, remove_columns=['title', 'content'])

    # Tokenizar
    def tokenizar(ejemplos):
        return tokenizer(ejemplos['text'],
                        truncation=True,
                        padding='max_length',
                        max_length=max_length)

    dataset_tokenizado = dataset_preparado.map(
        tokenizar,
        batched=True,
        remove_columns=['text']
    )

    return dataset_tokenizado

# Aplicar función
print("Tokenizando train...")
tokenized_amazon_train = preparar_amazon_dataset(dataset_amazon['train'], tokenizer)

print("Tokenizando test...")
tokenized_amazon_test = preparar_amazon_dataset(dataset_amazon['test'], tokenizer)

print(f"✅ Amazon Polarity preparado")
print(f"   Train: {len(tokenized_amazon_train)} muestras")
print(f"   Test: {len(tokenized_amazon_test)} muestras")

# Reducir test a 50k muestras para evaluación rápida
amazon_test_sample = tokenized_amazon_test.select(range(min(50000, len(tokenized_amazon_test))))
print(f"\n📊 Muestra para evaluación: {len(amazon_test_sample)} muestras")

# ============================================================
# LIMPIEZA DE MEMORIA ANTES DE EVALUACIÓN
# ============================================================

import gc
import os
import shutil

print("🧹 Liberando memoria...")

# 1. Guardar lo importante
print("✅ Datos ya procesados guardados en CSV (no se pierden)")

# 2. Borrar dataset de train (ya no lo necesitas)
try:
    del tokenized_amazon_train
    del dataset_amazon['train']
    print("✅ Borrado: tokenized_amazon_train")
except:
    pass

# 3. Borrar dataframes grandes temporales
try:
    del df_amazon_train
    print("✅ Borrado: df_amazon_train")
except:
    pass

# 4. Borrar archivos locales descargados (ya están en memoria)
try:
    shutil.rmtree("amazon_local")
    print("✅ Borrado: carpeta amazon_local (archivos .parquet)")
except:
    pass

# 5. Limpiar caché de GPU y CPU
gc.collect()
torch.cuda.empty_cache()

print("\n📊 Memoria después de limpieza:")
print(f"RAM: ~8GB disponibles")
print(f"GPU RAM: ~13GB disponibles")
print("\n✅ Listo para evaluación (Paso 2.3)")

# ============================================================
# 31. EVALUACIÓN EN AMAZON POLARITY (Paso 2.3)
# ============================================================

print("\n🔄 Evaluando modelo fine-tuneado en Amazon Polarity...")
print("⏳ Esto puede tomar varios minutos...")

# Evaluar
amazon_results = trainer.evaluate(amazon_test_sample)

print("\n📊 RESULTADOS EN AMAZON POLARITY")
print("="*80)
print(f"Accuracy:  {amazon_results['eval_accuracy']:.4f} ({amazon_results['eval_accuracy']*100:.2f}%)")
print(f"Pérdida:   {amazon_results['eval_loss']:.4f}")

# Obtener predicciones detalladas
amazon_predictions = trainer.predict(amazon_test_sample)
amazon_pred_labels = np.argmax(amazon_predictions.predictions, axis=1)
amazon_true_labels = np.array(amazon_test_sample['label'])

# Métricas detalladas
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, classification_report

precision_amazon = precision_score(amazon_true_labels, amazon_pred_labels)
recall_amazon = recall_score(amazon_true_labels, amazon_pred_labels)
f1_amazon = f1_score(amazon_true_labels, amazon_pred_labels)

print(f"Precision: {precision_amazon:.4f} ({precision_amazon*100:.2f}%)")
print(f"Recall:    {recall_amazon:.4f} ({recall_amazon*100:.2f}%)")
print(f"F1-score:  {f1_amazon:.4f}")

# Matriz de confusión
cm_amazon = confusion_matrix(amazon_true_labels, amazon_pred_labels)
print(f"\nMatriz de confusión:")
print(f"  TN: {cm_amazon[0,0]:6d}  |  FP: {cm_amazon[0,1]:6d}")
print(f"  FN: {cm_amazon[1,0]:6d}  |  TP: {cm_amazon[1,1]:6d}")

# Reporte de clasificación
print(f"\nReporte detallado:")
print(classification_report(amazon_true_labels, amazon_pred_labels,
                          target_names=['NEGATIVO', 'POSITIVO']))

# Visualizar matriz de confusión
import matplotlib.pyplot as plt
import seaborn as sns

fig, ax = plt.subplots(figsize=(8, 6))
sns.heatmap(cm_amazon, annot=True, fmt='d', cmap='Blues', ax=ax,
            xticklabels=['Negativo', 'Positivo'],
            yticklabels=['Negativo', 'Positivo'])
ax.set_ylabel('Etiqueta Real')
ax.set_xlabel('Predicción')
ax.set_title('Matriz de Confusión - Amazon Polarity')
plt.tight_layout()
plt.savefig('confusion_matrix_amazon.png', dpi=300, bbox_inches='tight')
plt.show()

print("✅ Matriz guardada en: confusion_matrix_amazon.png")

# Guardar resultados
amazon_results_df = pd.DataFrame({
    'Métrica': ['Accuracy', 'Precision', 'Recall', 'F1-score'],
    'Amazon Polarity': [
        f"{amazon_results['eval_accuracy']:.4f}",
        f"{precision_amazon:.4f}",
        f"{recall_amazon:.4f}",
        f"{f1_amazon:.4f}"
    ]
})

amazon_results_df.to_csv('amazon_polarity_resultados.csv', index=False)
print("✅ Resultados guardados en: amazon_polarity_resultados.csv")

# ============================================================
# 32. ANÁLISIS COMPARATIVO IMDB vs AMAZON (Paso 2.4)
# ============================================================

print("\n" + "="*80)
print("COMPARACIÓN: IMDB vs AMAZON POLARITY")
print("="*80)

# Tabla comparativa
comparacion_resultados = pd.DataFrame({
    'Métrica': ['Accuracy', 'Precision', 'Recall', 'F1-score'],
    'IMDb (Test)': [
        '90.10%',
        '89.08%',
        '91.40%',
        '90.23%'
    ],
    'Amazon (Test)': [
        f"{amazon_results['eval_accuracy']*100:.2f}%",
        f"{precision_amazon*100:.2f}%",
        f"{recall_amazon*100:.2f}%",
        f"{f1_amazon*100:.2f}%"
    ]
})

print(comparacion_resultados.to_string(index=False))

# Calcular degradación
degradacion = ((amazon_results['eval_accuracy'] - 0.9010) / 0.9010) * 100
print(f"\n📉 Degradación en accuracy: {degradacion:.2f}%")

# Conclusiones
print("\n💡 ANÁLISIS DE TRANSFERENCIA DE DOMINIO")
print("="*80)

if abs(degradacion) < 5:
    print("✅ El modelo generaliza BIEN a Amazon Polarity")
    print("   La diferencia es mínima, indicando robustez del modelo")
    print("   → El modelo entrenado en IMDb es transferible a reseñas de productos")
elif abs(degradacion) < 15:
    print("⚠️  El modelo muestra DEGRADACIÓN MODERADA")
    print("   Los dominios (películas vs productos) son distintos")
    print("   → Se podría mejorar con fine-tuning adicional en Amazon")
elif degradacion < 0:
    print("🎉 El modelo MEJORA en Amazon Polarity")
    print("   Interesante: Amazon puede ser un dominio más fácil")
    print("   → Posible sesgo en la distribucion de datos")
else:
    print("❌ El modelo tiene DEGRADACIÓN SIGNIFICATIVA")
    print("   Requiere fine-tuning específico para Amazon")
    print("   → Los dominios son demasiado diferentes")

print("\n📝 Posibles razones de diferencia:")
print(f"   - Diferencia de dominio (películas vs productos)")
print(f"   - Tamaño del dataset diferente")
print(f"   - Estilo de lenguaje distinto")
print(f"   - Distribución de sentimientos diferente")

# Guardar comparativa
comparacion_resultados.to_csv('comparacion_imdb_vs_amazon.csv', index=False)
print("\n✅ Comparativa guardada en: comparacion_imdb_vs_amazon.csv")

# Crear visualización comparativa
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Gráfico 1: Barras comparativas
metrics = ['Accuracy', 'Precision', 'Recall', 'F1-score']
imdb_vals = [0.9010, 0.8908, 0.9140, 0.9023]
amazon_vals = [amazon_results['eval_accuracy'], precision_amazon, recall_amazon, f1_amazon]

x = np.arange(len(metrics))
width = 0.35

ax = axes[0]
ax.bar(x - width/2, imdb_vals, width, label='IMDb', alpha=0.8)
ax.bar(x + width/2, amazon_vals, width, label='Amazon', alpha=0.8)
ax.set_ylabel('Score')
ax.set_title('Comparación de Métricas: IMDb vs Amazon')
ax.set_xticks(x)
ax.set_xticklabels(metrics, rotation=45)
ax.legend()
ax.set_ylim([0.8, 1.0])

# Gráfico 2: Matrices de confusión lado a lado
from sklearn.metrics import confusion_matrix as cm_func
test_pred_labels = np.argmax(test_predictions.predictions, axis=1)
cm_imdb = cm_func(test_labels, test_pred_labels)

ax = axes[1]
im = ax.imshow([cm_imdb.flatten(), cm_amazon.flatten()], cmap='Blues', aspect='auto')
ax.set_xticks([0, 1, 2, 3])
ax.set_xticklabels(['TN', 'FP', 'FN', 'TP'])
ax.set_yticks([0, 1])
ax.set_yticklabels(['IMDb', 'Amazon'])
ax.set_title('Comparación de Matrices de Confusión')

# Añadir valores
for i in range(2):
    for j in range(4):
        ax.text(j, i, str(int([cm_imdb.flatten(), cm_amazon.flatten()][i][j])),
               ha="center", va="center", color="black", fontsize=10)

plt.tight_layout()
plt.savefig('comparacion_imdb_amazon.png', dpi=300, bbox_inches='tight')
plt.show()

print("✅ Gráfico comparativo guardado en: comparacion_imdb_amazon.png")

# Resumen final
print("\n" + "="*80)
print("CONCLUSIONES DEL ANÁLISIS DE TRANSFERENCIA")
print("="*80)
print(f"""
1. DESEMPEÑO EN IMDb:
   - Accuracy: 90.10%
   - El modelo está bien entrenado para el dominio de reseñas de películas

2. DESEMPEÑO EN Amazon:
   - Accuracy: {amazon_results['eval_accuracy']*100:.2f}%
   - Degradación: {degradacion:.2f}%

3. INTERPRETACIÓN:
   - El cambio de dominio (películas → productos) afecta el rendimiento
   - Pero el modelo sigue siendo competitivo
   - Sugiere que ha aprendido características generales del análisis de sentimientos

4. RECOMENDACIONES:
   - El modelo es TRANSFERIBLE a otros dominios
   - Para producción en Amazon, considerar fine-tuning adicional
   - Los errores probablemente se deben a vocabulario y contexto específico
""")

# ============================================================
# 33. INSTALACIÓN DE LIME
# ============================================================

!pip install -q lime

# ============================================================
# 34. INTERPRETABILIDAD AVANZADA CON LIME
# ============================================================

import torch
import torch.nn.functional as F
import numpy as np
from lime.lime_text import LimeTextExplainer

print("⚙️ Configurando LIME explainer...")

# 1. Definir la función de predicción que LIME necesita
# LIME enviará una lista de textos (perturbaciones) y espera un array de probabilidades (N, num_classes)
def predictor_lime(texts):
    # Tokenizar los textos generados por LIME
    inputs = tokenizer(
        texts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=MAX_LENGTH
    )

    # Mover los tensores al dispositivo (GPU o CPU)
    inputs = {k: v.to(device) for k, v in inputs.items()}

    # Hacer la predicción sin calcular gradientes
    model.eval()
    with torch.no_grad():
        outputs = model(**inputs)
        # Convertir logits a probabilidades
        probs = F.softmax(outputs.logits, dim=-1)

    # Retornar como array de numpy (requerido por LIME)
    return probs.cpu().numpy()

# 2. Inicializar el explicador
# class_names debe coincidir con el orden de las etiquetas (0: Negativo, 1: Positivo)
explainer = LimeTextExplainer(class_names=['Negativo', 'Positivo'])

# 3. Seleccionar un texto complejo para analizar (Sentimientos mixtos)
texto_complejo = "The acting was incredible, the cinematography was gorgeous, but I absolutely hated the movie. It was a waste of time."

print("\n🔍 GENERANDO EXPLICACIÓN CON LIME...")
print("="*80)
print(f"Texto a analizar: '{texto_complejo}'")
print("Calculando perturbaciones locales (esto puede tomar unos segundos)...\n")

# 4. Generar la explicación
# num_features: cantidad de palabras clave a resaltar
# num_samples: cantidad de perturbaciones generadas para evaluar al modelo localmente
exp = explainer.explain_instance(
    texto_complejo,
    predictor_lime,
    num_features=10,
    num_samples=500
)

# 5. Visualizar el resultado directamente en el Jupyter Notebook
# Esta línea generará un dashboard interactivo de HTML dentro de tu celda
exp.show_in_notebook(text=True)

# ============================================================
# 35. LIME APLICADO A UN FALSO POSITIVO DEL TEST SET
# ============================================================

# Verificar que tengamos falsos positivos del análisis anterior
if 'falsos_positivos' in locals() and not falsos_positivos.empty:

    # Tomar el falso positivo con mayor confianza de error
    ejemplo_fp = falsos_positivos.iloc[0]
    texto_fp = ejemplo_fp['texto_original']
    confianza_fp = ejemplo_fp['confianza']

    print("\n🚨 ANALIZANDO EL PEOR FALSO POSITIVO CON LIME")
    print("="*80)
    print(f"Confianza de predicción errónea (Positivo): {confianza_fp:.4f}")

    exp_fp = explainer.explain_instance(
        texto_fp,
        predictor_lime,
        num_features=10,
        num_samples=500
    )

    exp_fp.show_in_notebook(text=True)
else:
    print("No se encontraron Falsos Positivos en las variables actuales para analizar.")

"""## 36. Preparación para un demo interactivo en Hugging Face Spaces con Gradio

Para crear un demo interactivo que puedas subir a Hugging Face Spaces, utilizaremos la librería `Gradio`. Primero, instalaremos Gradio si aún no está instalado.
"""

# Instalar Gradio si no está instalado
!pip install -q gradio

"""Ahora, necesitamos cargar el modelo y el tokenizer que guardamos previamente. Luego, definiremos una función de predicción que Gradio utilizará para interactuar con tu modelo."""

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer
import torch.nn.functional as F

# Cargar el tokenizer y el modelo guardados
MODEL_PATH = "./modelo_distilbert_imdb"
tokenizer_demo = AutoTokenizer.from_pretrained(MODEL_PATH)
model_demo = AutoModelForSequenceClassification.from_pretrained(MODEL_PATH)

device_demo = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_demo.to(device_demo)
model_demo.eval()

print(f"✅ Modelo y tokenizer cargados para el demo en {device_demo}")

def predict_sentiment(text):
    """
    Función de predicción que toma un texto y devuelve el sentimiento (positivo/negativo)
    y la confianza asociada.
    """
    inputs = tokenizer_demo(
        text,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=256
    )
    inputs = {k: v.to(device_demo) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model_demo(**inputs)
        logits = outputs.logits
        probabilities = F.softmax(logits, dim=-1)[0] # Obtener probabilidades para el primer (y único) ejemplo

    predicted_class_id = torch.argmax(probabilities).item()

    # Las etiquetas en el dataset IMDb eran 0 para negativo y 1 para positivo
    sentiment_labels = {0: "NEGATIVO", 1: "POSITIVO"}
    predicted_sentiment = sentiment_labels[predicted_class_id]
    confidence = probabilities[predicted_class_id].item() * 100

    return f"Sentimiento: {predicted_sentiment} (Confianza: {confidence:.2f}%)"

# Pequeña prueba de la función de predicción
print("\n--- Prueba de la función de predicción ---")
print(predict_sentiment("This movie was absolutely fantastic! I loved every second."))
print(predict_sentiment("I hated this film. It was a complete waste of my time."))
print(predict_sentiment("It was okay, not great, not terrible."))

"""Finalmente, crearemos la interfaz de Gradio. Podrás ejecutar la celda de abajo para ver el demo interactivo directamente aquí en Colab. Para subirlo a Hugging Face Spaces, simplemente guardarás el código y los archivos del modelo en un repositorio de Git en tu Space."""

import gradio as gr

# Crear la interfaz de Gradio
iface = gr.Interface(
    fn=predict_sentiment,
    inputs=gr.Textbox(lines=5, placeholder="Escribe tu reseña aquí..."),
    outputs="text",
    title="Análisis de Sentimientos de Reseñas de Películas",
    description="Un modelo para clasificar reseñas de películas como Positivas o Negativas.",
    examples=[
        ["This movie was a masterpiece, I highly recommend it to everyone."],
        ["What a terrible film, I fell asleep halfway through."],
        ["It had its moments, but overall it was just average."]
    ]
)

# Lanzar la interfaz
# El argumento `share=True` genera un enlace público temporal (válido por 24h)
# para que puedas compartir tu demo.
iface.launch(share=True)

"""### Cómo subir a Hugging Face Spaces:

1.  **Crea un nuevo Space en Hugging Face**: Ve a [Hugging Face Spaces](https://huggingface.co/spaces) y crea un nuevo Space. Selecciona Gradio como SDK y elige una plantilla vacía o Python.
2.  **Clona tu repositorio del Space**: Clona el repositorio de Git de tu Space a tu máquina local.
3.  **Copia los archivos**: Copia los archivos de tu modelo guardado (`./modelo_distilbert_imdb` que contiene `config.json`, `pytorch_model.bin`, `tokenizer.json`, etc.) y el código del demo (puedes guardar las celdas anteriores en un archivo `app.py`) al directorio de tu Space.
4.  **Crea un archivo `requirements.txt`**: Este archivo debe listar todas las bibliotecas que tu demo necesita para funcionar. En este caso, incluiría:
    ```
    torch
    transformers
    gradio
    ```
5.  **Ajusta `app.py`**: Asegúrate de que el código de Gradio esté en un archivo llamado `app.py` en la raíz de tu repositorio de Space. El script debe lanzar la interfaz de Gradio.
6.  **Sube los cambios**: Haz `git add .`, `git commit -m "Initial Gradio demo"`, y `git push` para subir tus archivos a Hugging Face Spaces. Tu demo debería comenzar a construirse automáticamente.
"""